repos:
  - repo: local
    hooks:
      - id: check-version-consistency
        name: Check version consistency
        entry: python3 dev/check_version_consistency.py
        language: system
        pass_filenames: false
        always_run: true
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.10
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy gny/
        language: system
        pass_filenames: false
        always_run: true
      - id: openapi-spec-validator
        name: openapi-spec-validator
        entry: openapi-spec-validator openapi.yaml
        language: system
        pass_filenames: false
        always_run: true
